### ISSUE TITLE
ControllerFactoryFilter::getController returns false

### ISSUE THREAD

**Issue by aydot** [lorenzo/piping-bag#7] opened 2015-04-09 00:51 UTC
ControllerFactoryFilter::getController returns false when trying to use controller method injection.
I see it returns false from here :
[https://github.com/lorenzo/piping-bag/blob/master/src/Routing/Filter/ControllerFactoryFilter.php#L93]
but I am calling from a controller, and I don't understand why it's returning false when there is definitely a controller.

**Comment by aydot** [comment] 2015-04-09 15:17
Also, the Injecting Dependencies in Controllers example code you have doesn't work for me. When I use the Piping::get('Classname'), it works. but when i inject the dependency, and put the annotation, it doesn't.

**Comment by lorenzo** [comment] 2015-04-09 16:53
I'll take a look at this soon.

**Comment by aydot** [comment] 2015-04-10 16:33
Had a chance to look at this yet ?

**Comment by lorenzo** [comment] 2015-04-11 14:10
I can confirm the bug...

**Comment by lorenzo** [comment] 2015-04-11 14:32
@aydot due to some changes I made earlier for performance, I had to change the way the plugin is installed. Check the new instructions https://github.com/lorenzo/piping-bag#configuration

In particular, you need to change

``` php
DispatcherFactory::add('ControllerFactory');
```

With the following:

``` php
use PipingBag\Di\PipingBag;
DispatcherFactory::add(PipingBag::get('PipingBag\Routing\Filter\ControllerFactoryFilter'));
```

**Comment by aydot** [comment] 2015-04-11 14:45
the controller action injection still doesn't work for me

**Comment by lorenzo** [comment] 2015-04-11 14:52
Tell me what you did, it works for me fine

**Comment by lorenzo** [comment] 2015-04-11 15:08
@aydot actually you are right, it does not work. I need to investigate further.

**Comment by aydot** [comment] 2015-04-13 17:51
have an idea when you'd be able to look into this? quick question, will this work for a Controller constructor injection just like Laravel does?

**Comment by lorenzo** [comment] 2015-04-13 18:28
Hey, I'm sorry about this issue. I'm currently sorting it out with Ray.Di creator, since I need a feature that is not currently supported in the library.

CakePHP already reserves the constructor of the controller, so adding more parameters to it will only feel awkward. Instead you can use use any other method to get your dependencies injected:

``` php
/**
 * @Inject
 */
public function postConstruct(Dep1 $dep, Dep2 $dep2 ....) {
}
```

I'll try to solve this issue as soon as possible. If you need any workaround please let me know. There are way to workaround this, but need some changes in Ray.Di to make this work in a generic way.

**Comment by aydot** [comment] 2015-04-13 18:47
How do I write test for the dependencies? Will I have to swap out the instance in the container?
I tried this code here but didn't work.

```
$container = new Container;
$browser = $this->getMock('Ikimea\Browser\Browser');
(new Bind($container, 'Ikimea\Browser\Browser'))->toInstance($browser);
```

**Comment by lorenzo** [comment] 2015-04-13 19:20
The best way is to create a new container with extra modules that you can use in the test. In general, this technique is used for integration testing and makes no much sense for unit testing since you should be passing the dependencies manually:

``` php
PipingBag::container($anotherInjectorInstance);
```

You can create the injector instance manually or by passing the result of calling `PipingBag::create($allModulesNeededForTest)`

**Comment by aydot** [comment] 2015-04-14 11:44
How would you test a code like this?

```
<?php
namespace App\View\Cell;

use Cake\View\Cell;
use PipingBag\Di\PipingBag as Di;
use Ikimea\Browser\Browser;

class BrowserCompatibilityCell extends Cell
{
    protected $_validCellOptions = [];

    public function display()
    {
        $browser = Di::get('Ikimea\Browser\Browser');
        $this->set('browser', $browser->getBrowser().' '.$browser->getVersion());
    }
}
```

Since I can't inject it's dependency via the constructor

**Comment by lorenzo** [comment] 2015-05-03 15:14
Closing this as it is working now

**Closed as completed by lorenzo** 2015-05-03 15:14 UTC
Labels: bug
